### PR TITLE
fix: compatibility with rocks-git.nvim

### LINKED ISSUE #4: Lazy loading with `event = 'DeferredUIEnter'` causes error
Hello, I am using `rocks-lazy` to lazy load `gitsigns.nvim` with `event = 'DeferredUIEnter`
But when I do `:Rocks sync` and open neovim I get this error.
image

# My neovim version:
```NVIM v0.11.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.1703358377
Run "nvim -V1 -v" for more info
```

# My rocks.nvim version 
`rocks.nvim = '2.32.1'`

# Steps to reproduce
add `event = 'DeferredUIEnter` to any of your plugins in your `rocks.toml` and call the setup function in one of your files

### PR DESCRIPTION
**Pull request by mrcjkb**
Fixes #4

### CODE REVIEW

File: lua/rocks-lazy/internal.lua [hunk 1]
```diff
@@ -9,9 +9,13 @@ function rocks_lazy.load()
     local user_rocks = api.get_user_rocks()
 
     local has_rocks_config, rocks_config = pcall(require, "rocks-config")
-    ---@type fun(name: string) | nil
-    local config_hook = has_rocks_config and type(rocks_config.configure) == "function" and rocks_config.configure
-        or nil
+    ---@param name string
+    local config_hook = function(name)
+        if has_rocks_config and type(rocks_config.configure) == "function"
```
Comment (mrcjkb) [inline lua/rocks-lazy/internal.lua:14]:
```suggestion
        if has_rocks_config and type(rocks_config.configure) == "function" then
```
